spring:
 application:
  name: jpahibernateservice
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
 datasource:
  url: jdbc:mysql://localhost:3306/tour_of_heroes?useSSL=false
  username: root
  password: Passw0rd#
 data:
  solr:
   host: http://localhost:8983/solr/
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
  hibernate:
   ddl-auto: update
server:
 port: 8083
security:
 basic:
  enabled: false
debug: true
logging:
 path: C:\\Users\\kamarnan\\OneDrive - Capgemini\\Spring-Kafka-Elastic\\jpa-hibernate\\
 file: C:\\Users\\kamarnan\\OneDrive - Capgemini\\Spring-Kafka-Elastic\\jpa-hibernate\\application.log
 level:
  root: WARN
---

spring:
 profiles: dev

---

spring:
 profiles: prod

